name: Destroy Infrastructure AWS

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
  workflow_dispatch:
    inputs:
      region:
        description: 'Target region'
        required: true
        default: 'us-east-1'
        type: choice
        options:
          - us-east-1
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ github.event.inputs.environment == 'dev' && secrets.AWS_ACCOUNT_ID_DEV || github.event.inputs.environment == 'staging' && secrets.AWS_ACCOUNT_ID_STAGING  || secrets.AWS_ACCOUNT_ID_PROD }}
  AWS_REGION: ${{ github.event.inputs.region }}
  ENVIRONMENT:  ${{ github.event.inputs.environment }}

jobs:
  validate-environment:
    name: Validate Environment
    runs-on: ${{ vars.RUNNER }}
    if: >
      (github.ref_name == 'dev' && github.event.inputs.environment == 'dev') ||
      (github.ref_name == 'main' && (github.event.inputs.environment == 'staging' || github.event.inputs.environment == 'production'))
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Validating Environment
        run: echo "Validating ${{ env.ENVIRONMENT }} environment from ${{ github.ref_name }} branch"

  destroy:
    name: Destroy Infra
    needs: validate-environment
    runs-on: ${{ vars.RUNNER }}
    environment: ${{ env.ENVIRONMENT }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Configure Environment
        run: echo "Deploying to ${{ env.ENVIRONMENT }} environment from ${{ github.ref_name }} branch"
      
      - name: Run Terraform Init
        working-directory: terraform
        run: |
          echo ${{ env.AWS_REGION }}
          terraform init \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="bucket=terraformstate001-${{ env.ENVIRONMENT }}" \
            -backend-config="key=${{ env.ENVIRONMENT }}/terraform.tfstate" \
            -backend-config="dynamodb_table=terraform-locks-${{ env.ENVIRONMENT }}"

      - name: Select or Create Workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{ env.ENVIRONMENT }} || terraform workspace new ${{ env.ENVIRONMENT }}

      - name: Destroy
        working-directory: terraform
        id: destroy
        run: |
          terraform destroy -var-file="environments/${{ env.ENVIRONMENT }}/terraform.tfvars" -auto-approve
      
