name: Build/Destroy Infrastructure

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform Action"
        required: true
        default: "build"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ github.event.inputs.region || 'us-east-1' }}
  BRANCH_NAME: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

jobs:
  infra-build:
    name: Build Infra
    runs-on:  ${{ vars.RUNNER }}
    if: ${{ github.event.inputs.action == 'build'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="bucket=terraformstate001-${{ env.BRANCH_NAME }}" \
            -backend-config="key=${{ env.BRANCH_NAME }}/terraform.tfstate" \
            -backend-config="dynamodb_table=terraform-locks-${{ env.BRANCH_NAME }}"

      - name: Select or Create Workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{ env.BRANCH_NAME }} || terraform workspace new ${{ env.BRANCH_NAME }}

      - name: Run Plan
        working-directory: terraform
        id: plan
        run: |
          terraform plan -var-file="environments/${{ env.BRANCH_NAME }}/terraform.tfvars" -out=${{ env.BRANCH_NAME }}-plan.out
      
      - name: Run Apply
        working-directory: terraform
        run: |
          terraform apply ${{ env.BRANCH_NAME }}-plan.out

  infra-destroy:
    name: Destroy Infra on Branch Deletion
    runs-on: ${{ vars.RUNNER }}
    if: ${{ github.event.inputs.action == 'destroy'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init -backend-config="key=${{ env.BRANCH_NAME }}/terraform.tfstate"

      - name: Select or Create Workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{ env.BRANCH_NAME }}

      - name: Run Destroy
        working-directory: terraform
        run: |
          terraform destroy -var-file="environments/${{ env.BRANCH_NAME }}/terraform.tfvars" -auto-approve
