name: Build/Destroy Infrastructure

on:
  push:
    branches:
      - dev
      - staging
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ github.event.inputs.region || 'us-east-1' }}
  AWS_DOMAIN: ${{ github.event.inputs.domain || 'artifacts' }} 
  AWS_REPO: ${{ github.event.inputs.repo || 'Artifacts' }}
  BRANCH_NAME: ${{ github.ref_name == 'refs/heads/main' && 'prod' || github.ref_name }}

jobs:
  infra-build:
    name: Build Infra
    runs-on:  ${{ vars.RUNNER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Change Folder
        run: |
          cd Infrastructure/terraform
      
      # - name: Create New Workspace
      #   run: |
      #     terraform workspace new ${{ env.BRANCH_NAME }}
      
      # - name: Select Workspace
      #   run: |
      #     terraform workspace select ${{ env.BRANCH_NAME }}
      
      # - name: Run Plan
      #   run: |
      #     terraform plan -var-file="environments/${{ env.BRANCH_NAME }}/terraform.tfvars" -out=${{ env.BRANCH_NAME }}-plan.out
      
      # - name: Run Apply
      #   run: |
      #     terraform apply ${{ env.BRANCH_NAME }}-plan.out

  infra-destroy:
    name: Destroy Infra
    runs-on: ${{ vars.RUNNER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change Folder
        run: |
          cd Infrastructure/terraform
      
      # - name: Run Destroy
      #   run: |
      #     terraform destroy -var-file="environments/${{ env.BRANCH_NAME }}/terraform.tfvars" -auto-approve
