name: Build and Upload React App

on:
  push:
    branches:
      - dev
      - staging
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ github.event.inputs.region || 'us-east-1' }}
  AWS_DOMAIN: ${{ github.event.inputs.domain || 'artifacts' }} 
  AWS_REPO: ${{ github.event.inputs.repo || 'Artifacts' }}
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build:
    name: Build Static Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


  publish:
    name: Deploy to AWS Amplify
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
