name: Build/Destroy Infrastructure

on:
  push:
    branches:
      - dev
      - staging
      - main
  delete:
    branches:
      - dev
      - staging

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ github.event.inputs.region || 'us-east-1' }}
  BRANCH_NAME: ${{ github.ref_name == 'refs/heads/main' && 'prod' || github.ref_name }}

jobs:
  infra-build:
    name: Build Infra
    runs-on:  ${{ vars.RUNNER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Terraform Init
        working-directory: terraform
        run: |
          terraform init -backend-config="key=${{ env.BRANCH_NAME }}/terraform.tfstate"

      - name: Select or Create Workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{ env.BRANCH_NAME }} || terraform workspace new ${{ env.BRANCH_NAME }}

      - name: Run Plan
        working-directory: terraform
        id: plan
        run: |
          terraform plan -var-file="environments/${{ env.BRANCH_NAME }}/terraform.tfvars" -out=${{ env.BRANCH_NAME }}-plan.out
      
      - name: Run Apply
        working-directory: terraform
        if: steps.plan.outputs.changes == 'true'
        run: |
          terraform apply ${{ env.BRANCH_NAME }}-plan.out

  infra-destroy:
    name: Destroy Infra on Branch Deletion
    runs-on: ${{ vars.RUNNER }}
    if: github.event.ref_type == 'branch' && github.event.deleted == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init

      - name: Select or Create Workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{ env.BRANCH_NAME }}

      - name: Run Destroy
        working-directory: terraform
        run: |
          terraform destroy -var-file="environments/environments/${{ env.BRANCH_NAME }}/terraform.tfvars" -auto-approve
