name: Infrastructure Pipeline

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action'
        required: true
        type: string
      stage_name:
        description: 'Stage name'
        default: dev
        required: true
        type: string
      aws_region:
        description: 'AWS region'
        required: false
        default: 'us-east-1'
        type: string

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ inputs.aws_region }}

jobs:
  infra-build:
    name: Build Infra
    runs-on: ${{ vars.RUNNER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="bucket=terraformstate001-${{ inputs.stage_name }}" \
            -backend-config="key=${{ inputs.stage_name }}/terraform.tfstate" \
            -backend-config="dynamodb_table=terraform-locks-${{ inputs.stage_name }}"

      - name: Select or Create Workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{ inputs.stage_name }} || terraform workspace new ${{ inputs.stage_name }}

      - name: Run Plan or Destroy
        working-directory: terraform
        id: plan_or_destroy
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            terraform plan -var-file="environments/${{ inputs.stage_name }}/terraform.tfvars" -out=${{ inputs.stage_name }}-plan.out
          elif [ "${{ inputs.action }}" == "build" ]; then
            terraform plan -var-file="environments/${{ inputs.stage_name }}/terraform.tfvars" -out=${{ inputs.stage_name }}-plan.out
          elif [ "${{ inputs.action }}" == "destroy" ]; then
            terraform destroy -var-file="environments/${{ inputs.stage_name }}/terraform.tfvars" -auto-approve
          fi

      - name: Run Apply (if building)
        if: ${{ github.event_name == 'push' || inputs.action == 'build' }}
        working-directory: terraform
        run: |
          terraform apply ${{ inputs.stage_name }}-plan.out